language: python
sudo: required
dist: trusty
python:
- '2.7'
- '3.4'
cache: pip
before_install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
- chmod +x miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda update --yes conda
- conda install --yes python="$TRAVIS_PYTHON_VERSION" numpy scipy matplotlib sympy networkx
    nose h5py pexpect pandas
- if [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]]; then
    pip install orange3;
  else
    pip install orange;
  fi
- pip install pygraphviz
- pip install python-coveralls
- pip install -r requirements.txt

install:
  python setup.py build --build-lib=build/lib
script:
  nosetests build/lib/magine --with-coverage --cover-inclusive --cover-package=build/lib/magine
  --ignore-files=build/lib/magine/networks/calculate_correlation_network.py
after_success:
  coveralls
